import SwiftUI
import WidgetKit

// Widget extension entry point.
//
// This target compiles ONLY the files in Widgets/ plus
// DarulIrfanApp/Core/Shared/ (see project.yml). Nothing in this target may
// reference the app's models, services, or design system — every piece of
// data arrives through `PrayerWidgetSnapshot`, which the app writes into the
// shared App Group container after each prayer-time recalculation.
//
// NOTE: Widgets/Info.plist and Widgets/DarulIrfanWidgets.entitlements are
// generated by XcodeGen from project.yml — they must not be created by hand.

@main
struct DarulIrfanWidgets: WidgetBundle {
    var body: some Widget {
        NextPrayerWidget()
        TodayTimesWidget()
    }
}

// MARK: - Local palette

/// The widget target does not compile the app's `Theme.swift`, so the brand
/// palette (deep emerald, warm cream, restrained gold) is redeclared here
/// with the same values. Light/dark variants are resolved through the view's
/// `colorScheme` environment because widgets render outside the app's theme.
enum WidgetPalette {
    // Light appearance
    static let emerald = Color(red: 0.043, green: 0.431, blue: 0.310)        // #0B6E4F
    static let cream = Color(red: 0.965, green: 0.953, blue: 0.925)          // #F6F3EC
    static let gold = Color(red: 0.788, green: 0.635, blue: 0.294)           // #C9A24B
    static let ink = Color(red: 0.110, green: 0.110, blue: 0.110)            // #1C1C1C
    static let mutedGray = Color(red: 0.420, green: 0.420, blue: 0.420)      // #6B6B6B

    // Dark appearance
    static let emeraldDark = Color(red: 0.298, green: 0.639, blue: 0.514)    // #4CA383
    static let creamDark = Color(red: 0.078, green: 0.090, blue: 0.078)      // #141714
    static let goldDark = Color(red: 0.851, green: 0.737, blue: 0.447)       // #D9BC72
    static let inkDark = Color(red: 0.949, green: 0.937, blue: 0.902)        // #F2EFE6
    static let mutedGrayDark = Color(red: 0.659, green: 0.651, blue: 0.612)  // #A8A69C

    /// Warm cream in light mode, deep green-tinted charcoal in dark mode.
    static func background(for scheme: ColorScheme) -> Color {
        scheme == .dark ? creamDark : cream
    }

    static func emeraldTone(for scheme: ColorScheme) -> Color {
        scheme == .dark ? emeraldDark : emerald
    }

    static func goldTone(for scheme: ColorScheme) -> Color {
        scheme == .dark ? goldDark : gold
    }

    static func textTone(for scheme: ColorScheme) -> Color {
        scheme == .dark ? inkDark : ink
    }

    static func mutedTone(for scheme: ColorScheme) -> Color {
        scheme == .dark ? mutedGrayDark : mutedGray
    }
}

// MARK: - Empty state

/// Shown by every widget family when no snapshot has been written yet
/// (first launch, or the App Group file was cleared).
struct WidgetEmptyStateView: View {
    @Environment(\.widgetFamily) private var family
    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        switch family {
        case .accessoryInline:
            Text("Open Darul Irfan to set up prayer times")
        case .accessoryCircular:
            ZStack {
                AccessoryWidgetBackground()
                Image(systemName: "moon.stars")
                    .font(.title3)
            }
            .accessibilityLabel(Text("Open Darul Irfan to set up prayer times"))
        case .accessoryRectangular:
            VStack(alignment: .leading, spacing: 2) {
                Text("Darul Irfan")
                    .font(.headline)
                Text("Open Darul Irfan to set up prayer times")
                    .font(.caption2)
            }
        default:
            VStack(spacing: 6) {
                Image(systemName: "moon.stars")
                    .font(.title2)
                    .foregroundStyle(WidgetPalette.goldTone(for: colorScheme))
                Text("Open Darul Irfan to set up prayer times")
                    .font(.footnote)
                    .multilineTextAlignment(.center)
                    .foregroundStyle(WidgetPalette.textTone(for: colorScheme))
            }
            .padding(4)
        }
    }
}

// MARK: - Sample data for placeholders and widget-gallery previews

extension PrayerWidgetSnapshot {
    /// A fabricated but plausible snapshot used for `placeholder(in:)` and
    /// gallery previews only. Real timelines always read the App Group file.
    static func sample(referenceDate: Date = Date()) -> PrayerWidgetSnapshot {
        let calendar = Calendar.current
        let startOfDay = calendar.startOfDay(for: referenceDate)

        func time(_ hour: Int, _ minute: Int, dayOffset: Int) -> Date {
            let day = calendar.date(byAdding: .day, value: dayOffset, to: startOfDay) ?? startOfDay
            return calendar.date(bySettingHour: hour, minute: minute, second: 0, of: day) ?? day
        }

        var times: [WidgetPrayerTime] = []
        for dayOffset in 0...2 {
            times.append(WidgetPrayerTime(prayerKey: "fajr", displayName: "Fajr", time: time(4, 32, dayOffset: dayOffset), isObligatory: true))
            times.append(WidgetPrayerTime(prayerKey: "sunrise", displayName: "Sunrise", time: time(5, 58, dayOffset: dayOffset), isObligatory: false))
            times.append(WidgetPrayerTime(prayerKey: "dhuhr", displayName: "Dhuhr", time: time(12, 24, dayOffset: dayOffset), isObligatory: true))
            times.append(WidgetPrayerTime(prayerKey: "asr", displayName: "Asr", time: time(16, 12, dayOffset: dayOffset), isObligatory: true))
            times.append(WidgetPrayerTime(prayerKey: "maghrib", displayName: "Maghrib", time: time(19, 5, dayOffset: dayOffset), isObligatory: true))
            times.append(WidgetPrayerTime(prayerKey: "isha", displayName: "Isha", time: time(20, 31, dayOffset: dayOffset), isObligatory: true))
        }

        return PrayerWidgetSnapshot(
            generatedAt: referenceDate,
            placeName: "Chakwal",
            upcomingTimes: times,
            hijriDateText: "15 Muharram 1448",
            suhoorEndsAt: nil,
            iftarAt: nil
        )
    }
}
