#!/usr/bin/env python3
"""Vet the packaged Sahih al-Bukhari pack and write a human report.

Every figure below is computed from the final, deduplicated pack that actually
ships — nothing is copied from upstream metadata or from the catalogue. Run:

    python Tools/Hadith/vet_bukhari.py            # print + write Docs report
"""
from __future__ import annotations
import json, hashlib, unicodedata
from pathlib import Path
from collections import Counter

IOS = Path(__file__).resolve().parents[2]
REPO = IOS.parent
SEED = IOS / "DarulIrfanApp/Resources/SeedData"
PLATFORMS = {
    "iOS": SEED,
    "Android": REPO / "DarulIrfanAndroid/app/src/main/assets/seed",
    "HarmonyOS": REPO / "DarulIrfanHarmony/entry/src/main/resources/rawfile/seed",
    "Web": REPO / "DarulIrfanWeb/content",
}
SUNNAH_MAX_REF = 7563          # last reference number on sunnah.com/bukhari
SUNNAH_BOOKS = 97

# Mojibake signatures: Latin-1/UTF-8 double-decode artefacts.
MOJIBAKE = ["Ã¢", "Ã©", "Ã¨", "Ã¯", "Ã±", "Ã¼", "Ã—", "Ã˜", "Â»", "Â«", "â€™", "â€œ", "â€"]


def main() -> None:
    recs = json.loads((SEED / "hadith_bukhari.json").read_text(encoding="utf-8"))
    catalog = json.loads((SEED / "hadith_books.json").read_text(encoding="utf-8"))
    bukhari = next(b for b in catalog["books"] if b["id"] == "bukhari")
    idx = json.loads((IOS / "Tools/Hadith/sunnah_bukhari_books.json").read_text(encoding="utf-8"))["books"]

    n = len(recs)
    cids = [r["canonicalID"] for r in recs]
    disp = [r["displayNumber"] for r in recs]
    seqs = [r["sourceSequence"] for r in recs]

    # Key integrity
    dup_cid = [k for k, c in Counter(cids).items() if c > 1]
    dup_disp = [k for k, c in Counter(disp).items() if c > 1]
    dup_seq = [k for k, c in Counter(seqs).items() if c > 1]
    roundtrip_bad = [r["canonicalID"] for r in recs
                     if r["canonicalID"] != f"bukhari|{r['displayNumber']}|{r['sourceSequence']}"]
    major_bad = []
    for r in recs:
        major, _, minor = str(r["displayNumber"]).partition(".")
        if str(r["numberMajor"]) != major:
            major_bad.append(r["displayNumber"])
        if minor and str(r.get("numberMinor")) != str(int(minor)):
            major_bad.append(r["displayNumber"])
        if not minor and r.get("numberMinor") is not None:
            major_bad.append(r["displayNumber"])

    subs = sorted((r["displayNumber"] for r in recs if r.get("numberMinor") is not None),
                  key=lambda s: (int(s.split(".")[0]), int(s.split(".")[1])))
    majors = sorted(set(r["numberMajor"] for r in recs))
    missing_ref_numbers = [i for i in range(1, SUNNAH_MAX_REF + 1) if i not in set(majors)]

    # Language coverage
    miss = {"ar": [], "en": [], "ur": []}
    for r in recs:
        for lang in ("ar", "en", "ur"):
            if not (r.get(f"text_{lang}") or "").strip():
                miss[lang].append(r["displayNumber"])
    ar_en_only_ur = [r["displayNumber"] for r in recs
                     if not (r.get("text_ar") or "").strip()
                     and not (r.get("text_en") or "").strip()
                     and (r.get("text_ur") or "").strip()]
    fully_empty = [r["displayNumber"] for r in recs
                   if not any((r.get(f"text_{l}") or "").strip() for l in ("ar", "en", "ur"))]

    # Encoding
    ufffd = sum((r.get(f"text_{l}") or "").count("�") for r in recs for l in ("ar", "en", "ur"))
    ufffd_recs = sorted({r["displayNumber"] for r in recs
                         for l in ("ar", "en", "ur") if "�" in (r.get(f"text_{l}") or "")})
    mojibake_hits = []
    for r in recs:
        for l in ("ar", "en", "ur"):
            t = r.get(f"text_{l}") or ""
            for m in MOJIBAKE:
                if m in t:
                    mojibake_hits.append(f"{r['displayNumber']}[{l}]:{m}")

    # Book grouping
    sec_counts = Counter(r["sourceBook"] for r in recs)
    unassigned = [r["displayNumber"] for r in recs if r.get("sourceBook") is None]
    sections = bukhari.get("sections", [])
    catalog_sec_sum = sum(s["hadithCount"] for s in sections)
    sec_mismatch = [s["number"] for s in sections if s["hadithCount"] != sec_counts.get(s["number"], 0)]

    # Cross-platform hashes
    hashes = {}
    for name, d in PLATFORMS.items():
        p = d / "hadith_bukhari.json"
        hashes[name] = hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else "MISSING"
    identical = len(set(hashes.values())) == 1

    ok = (not dup_cid and not dup_disp and not dup_seq and not roundtrip_bad
          and not major_bad and not unassigned and not fully_empty
          and not mojibake_hits and not sec_mismatch and identical
          and bukhari["hadithCount"] == n == catalog_sec_sum)

    L = []
    L.append("# Sahih al-Bukhari — rebuild vetting report")
    L.append("")
    L.append(f"_Generated by `Tools/Hadith/vet_bukhari.py` from the packaged pack. "
             f"Every number is computed from the shipped, deduplicated records._")
    L.append("")
    L.append(f"**Result: {'PASS — no integrity violations' if ok else 'FAIL — see flagged sections'}.**")
    L.append("")
    L.append("## Provenance & method")
    L.append("")
    L.append("- **Text (Arabic / English):** the public-domain (Unlicense) `fawazahmed0/hadith-api` "
             "corpus, a byte-for-byte mirror of sunnah.com — identical Arabic and identical English "
             "(Dr. M. Muhsin Khan), carrying sunnah.com's exact reference numbers **including "
             "sub-numbered narrations** (402.2, 690.2, 1390.2/.3, …) and sunnah.com's in-book references.")
    L.append("- **Book (kitab) structure:** taken directly from **https://sunnah.com/bukhari** — the "
             "97-book division with each book's English and Arabic title. Every narration is grouped "
             "under its book so the reader matches sunnah.com's navigation.")
    L.append("- **Urdu:** sunnah.com hosts **no Urdu translation for Sahih al-Bukhari** (verified live: "
             "the site's Urdu toggle loads nothing for this collection and fires no request). The Urdu "
             "shipped here is the hadith-api public-domain Urdu, kept as an honest bonus and marked "
             "**missing** on the narrations the source itself lacks — never back-filled from another language.")
    L.append("- **Grades:** sunnah.com prints no grade line for Bukhari (the whole collection is ṣaḥīḥ by "
             "definition), so no grade is fabricated.")
    L.append("")
    L.append("## Counts & reconciliation with sunnah.com")
    L.append("")
    L.append(f"- Packaged narrations: **{n:,}**")
    L.append(f"- Catalogue `hadithCount` for bukhari: **{bukhari['hadithCount']:,}** "
             f"({'matches the pack exactly' if bukhari['hadithCount']==n else 'MISMATCH'})")
    L.append(f"- Sum of the 97 catalogue section counts: **{catalog_sec_sum:,}** "
             f"({'matches the pack' if catalog_sec_sum==n else 'MISMATCH'})")
    L.append(f"- sunnah.com states \"over 7500 hadith (with repetitions) in 97 books\"; its last "
             f"reference number is **{SUNNAH_MAX_REF:,}**. Our highest whole reference is **{max(majors):,}**.")
    L.append(f"- Whole reference numbers 1–{SUNNAH_MAX_REF} that carry no narration: "
             f"**{len(missing_ref_numbers)}** — `{missing_ref_numbers}`. These are sunnah.com's own "
             f"merged/placeholder reference numbers (e.g. `bukhari:5710` returns an empty page on "
             f"sunnah.com itself); they are **not** missing hadith.")
    L.append(f"- Sub-numbered narrations preserved losslessly: **{len(subs)}** — `{subs}`")
    L.append("")
    L.append("## Key & schema integrity")
    L.append("")
    L.append(f"- Duplicate `canonicalID`: **{len(dup_cid)}**")
    L.append(f"- Duplicate `displayNumber`: **{len(dup_disp)}**")
    L.append(f"- Duplicate `sourceSequence`: **{len(dup_seq)}**")
    L.append(f"- `canonicalID` != `bukhari|displayNumber|sourceSequence`: **{len(roundtrip_bad)}**")
    L.append(f"- `numberMajor`/`numberMinor` inconsistent with `displayNumber`: **{len(major_bad)}**")
    L.append("")
    L.append("## Book grouping (kitab)")
    L.append("")
    L.append(f"- Books: **{len(sections)}** (sunnah.com has {SUNNAH_BOOKS})")
    L.append(f"- Narrations not assigned to any book: **{len(unassigned)}**")
    L.append(f"- Section counts recomputed from the pack that disagree with the catalogue: **{len(sec_mismatch)}**")
    L.append(f"- Book size range: {min(sec_counts.values())}–{max(sec_counts.values())} narrations")
    L.append("")
    L.append("## Language coverage (honest, source-limited)")
    L.append("")
    L.append(f"- Arabic present: **{n-len(miss['ar']):,}** / {n:,}  (missing {len(miss['ar'])})")
    L.append(f"- English present: **{n-len(miss['en']):,}** / {n:,}  (missing {len(miss['en'])})")
    L.append(f"- Urdu present: **{n-len(miss['ur']):,}** / {n:,}  (missing {len(miss['ur'])}, "
             f"shown as *missing* in the reader — sunnah.com has no Urdu for Bukhari)")
    L.append(f"- Narrations with only Urdu (Arabic & English absent upstream): **{len(ar_en_only_ur)}** — "
             f"`{ar_en_only_ur}` (sunnah.com merges these into an adjacent reference number)")
    L.append(f"- Narrations empty in **all three** languages (must be 0): **{len(fully_empty)}**")
    L.append("")
    L.append("## Encoding")
    L.append("")
    L.append(f"- U+FFFD replacement characters: **{ufffd}** across **{len(ufffd_recs)}** narrations — "
             f"inherited from the upstream Arabic decode, tracked in "
             f"`Tools/ContentIntegrity/known_upstream_defects.json`, unchanged by this rebuild.")
    L.append(f"- Double-decode mojibake signatures found: **{len(mojibake_hits)}** (must be 0)")
    L.append("")
    L.append("## Cross-platform parity")
    L.append("")
    for name, h in hashes.items():
        L.append(f"- {name}: `{h[:16] if h!='MISSING' else h}`")
    L.append(f"- All four identical: **{identical}**")
    L.append("")
    report = "\n".join(L) + "\n"
    out = IOS / "Docs/HADITH_BUKHARI_VETTING.md"
    out.write_text(report, encoding="utf-8", newline="\n")
    print(report)
    print(f"[written] {out}")
    print("OVERALL:", "PASS" if ok else "FAIL")


if __name__ == "__main__":
    main()
